### ISSUE TITLE
Set hero image max-width to match the masthead

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#17]
I think the `max-width` on the `.hero` element should be `1100px` instead of `1060px` so it matches the `#masthead`. It should also be changed in the `add_image_size( 'hero' )` function.

<img width="1266" alt="screen shot 2016-06-13 at 5 45 21 pm" src="https://cloud.githubusercontent.com/assets/522158/16025706/a2e8cdcc-318e-11e6-8c23-804b9cd16e91.png">

**Comment by chriswallace** [comment]
I think the reason we did this was that the content below in a Beaver Builder layout adds 20px of padding to the left and right, so we wanted to line the hero image up with the content below:

http://lift.d.pr/1lAv5

**Comment by fjarrett** [comment]
@schrapel @chriswallace Fair enough. Now that #20 is fixed it's less of a concern to me.

However, I'm concerned about image degradation when viewing the site in **Full Width Header / Footer** mode from a very large screen. On my 27" 4K monitor, the image quality is pretty bad. What do you think about adding a `hero-2x` size and using that when this mode is enabled?

```php
add_image_size( 'hero-2x', 2120, 1100, array( 'center', 'center' ) );
```

Or is there a better way to handle this? I know the use sees this message:

> While you can crop images to your liking after clicking Add new image, your theme recommends a header size of 1060 × 550 pixels.

**Comment by schrapel** [comment]
I agree on using a different image size for retina screens. We discussed this internally previously and it was something we were going to revisit. 

Since the hero is content managed it's hard to know what the height of the element is going to be. So that's hard to know what image dimensions to use. 1060 x 550 was purely in the design.

There is some reason to use something like the code below, so that if the user intentionally uses multiple widgets they can use a taller image. But if they upload really large images, they may remain largeish. 

```
add_image_size( 'hero', 1060, 9999, array( 'center', 'center' ) );
add_image_size( 'hero-2x', 2120, 9999, array( 'center', 'center' ) );
```

If this is the way we do it we should update the dimensions here to at least match 2120, 1100 so the user is clear they need a image of that size for retina screens

```
add_theme_support( 'custom-header', array(
		'default-image'          => get_stylesheet_directory_uri() . '/assets/images/hero.png',
		'width'                  => 1060,
		'height'                 => 550,
		'flex-height'            => true,
		'flex-width'             => false,
		'uploads'                => true,
	) );
```

Food for thought. I'm not entirely sure about the best way to approach this
