### ISSUE TITLE
Remove background color style from header

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#20]
The `#masthead` element should not have a background color (currently forced to be `#ffffff`) so it inherits whatever background color the user selects.

<img width="703" alt="screen shot 2016-06-13 at 5 53 29 pm" src="https://cloud.githubusercontent.com/assets/522158/16025867/cb1f5490-318f-11e6-8557-4262f9c0d810.png">

**Comment by schrapel** [comment]
@fjarrett there was a background here since the header is in a fixed position on mobile.

**Comment by fjarrett** [comment]
Got it. So the fix would be to target `#masthead` with whatever the Background Color setting is?

**Comment by schrapel** [comment]
Since the header is no longer fixed (#25) this is no longer needed. I've also removed the `#fff` background on the footer elements also. 

However, I'll need to grab the background color and apply to other elements like the navigation and buttons. I'll tackle this with the color scheme / customizer issues.

**Comment by fjarrett** [comment]
@schrapel Sounds good. I'll close this since the issue described has been resolved.
